### ISSUE TITLE
When stream starts, downloader always falls back to worse quality if a 3Mbit quality is selected

### ISSUE THREAD

**Issue by LittleVulpix** [HoloArchivists/fc2-live-dl#17]
I think it is related to / has symptoms of https://github.com/HoloArchivists/fc2-live-dl/issues/16 

If you use the autodl watcher with config that requests 3Mbps stream for example, it will never work. But if you wait a few seconds and simply restart (the same) command, it will grab the stream just fine at the high quality.

I am not sure why this is; maybe the 3mbps option isn't available immediately upon the start of a stream which is when the downloader tries to start the download?

I am not sure how to get around this, maybe it could keep trying to query if a better quality is available even while it's already downloading a stream; and auto-switch to it when it becomes available?

Right now what I'm doing is I wait for it to start downloading and then I immediately rerun the same command at which point it starts downloading at the highest quality without issues.

EDIT: not sure if it matters; I'm running it in WSL2.

**Comment by LittleVulpix** [comment]
I was basically able to confirm my suspicion. The higher qualities aren't available @ stream start time. If you retry (approx 15-30 seconds later?), the higher quality is available and you can begin downloading.

I wonder if it makes sense to implement some kind of "wait for higher quality up to X seconds" switch, because currently the behavior results in always downloading lower quality (unless you set a longer checking period and manage to check ~30+ seconds after the stream already started by chance).

**Comment by hizkifw** [comment]
Interesting, thanks for the report! I think I can come up with a patch real quick.

**Comment by hizkifw** [comment]
I've released version 2.1.0 on PyPI that adds a new configuration option `--wait-for-quality-timeout`, defaults to 15 seconds. Please try updating and let me know if you have any issues with it!

**Comment by LittleVulpix** [comment]
Thanks! The streamer streams once a week or so, so I'll know next week!

**Comment by LittleVulpix** [comment]
@hizkifw , perfection. Works exactly as expected. Thank you so much.

![image](https://user-images.githubusercontent.com/8679333/161392742-7173447d-1003-4382-8811-084a6b404d97.png)

**Comment by hizkifw** [comment]
Awesome, that's good to hear.
