### ISSUE TITLE
Cloudflare blocking this tool

### ISSUE THREAD

**Issue by FaySmash** [HoloArchivists/fc2-live-dl#32]
The download still works but only a two second still image gets downloaded with the following text:

> This video has been restricted. Streaming video from Cloudflare's basic service is a violation of the Terms of Service. Please visit cfl.re/tos to learn more.

**Comment by hizkifw** [comment]
This seemed to be a temporary issue on FC2's side. That video only appears when the site owner enables Cloudflare caching on videos and live stream segments, which is against TOS. There's nothing that can be done from our side.
