### ISSUE TITLE
How can I work around Login Required streams?

### ISSUE THREAD

**Issue by PengBooz** [HoloArchivists/fc2-live-dl#33]
Is there a way to do that?

**Comment by hizkifw** [comment]
You can use extensions that can extract cookies from your browser, and then give the cookies file to fc2-live-dl with the `--cookies` flag.

1. Log in to FC2 using your browser
2. Install an extension
  - Firefox: https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/
  - Chrome: https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en
3. Use extension to export cookies.txt in Netscape format
4. Run with `fc2-live-dl --cookies C:\somewhere\cookies.txt https://...`

If you get redirected to livechatfc2.com you can still use the cookies from there, just edit your cookies.txt file and replace the domain with live.fc2.com.

**Comment by PengBooz** [comment]
Thanks it worked.
