### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by kokorobeats** [HoloArchivists/fc2-live-dl#35]
Hello, to be precise, this is not an issue, but a feature request, requesting to add a function to upload the recorded file to Google Drive (or one drive) through rclone, and delete the local file after the upload is completed to save storage space

**Comment by hizkifw** [comment]
Hello,

That's out of the scope of this project. You can either set up a cron job to run rclone automatically, or set fc2-live-dl to download to an rclone mount.

**Comment by kokorobeats** [comment]
Hello, I used rclone to mount Google Drive on a vps, how do I set fc2-live-dl to download to the folder mounted by rclone? please guide me

**Comment by hizkifw** [comment]
@kokorobeats If you're using autofc2, you can set it in the `outtmpl` section of `autofc2.json`.

**Comment by kokorobeats** [comment]
I'm sorry, I haven't figured it out after researching for a long time, so I have to ask again,
I try to write rclone move /root/fc2-download remote:video/%(channel_name)s %(_en_name)s/%(title)s.%(ext)s" in the outtmpl column

But this will only generate a new folder to store the downloaded video files, the video files have not been moved to Google Drive

I'm sure the configuration of rclone is correct, and I can successfully move files using the rclone move command alone.

I think there must be something that I didn't fully understand or misunderstood.

**Comment by hizkifw** [comment]
You can set up an [rclone mount](https://rclone.org/commands/rclone_mount/), which will create a virtual folder that's actually your rclone remote. Then you can set the outtmpl path to the path of the mount.

For example, you can create a mount point in `/mnt/fc2`:

```sh
# Create the mount point
mkdir -p /mnt/fc2

# Create the mount
rclone mount myremote:some/folder /mnt/fc2
```

Then set `outtmpl` to `/mnt/fc2/%(channel_name)s %(_en_name)s/%(title)s.%(ext)s`

---

Alternatively you can create a folder where you temporarily store the recordings, then periodically run `rclone copy` from that folder to your remote, and create another task to periodically delete old recordings from that folder.

**Comment by kokorobeats** [comment]
Thank you for your patient teaching, I finally configured successfully, thank you!
