### ISSUE TITLE
[main] FileNotFoundError

### ISSUE THREAD

**Issue by urdtex** [HoloArchivists/fc2-live-dl#41]
![Capture](https://github.com/HoloArchivists/fc2-live-dl/assets/134232222/a0144cac-c770-4205-b7e0-3530feb363fc)

**Comment by hizkifw** [comment]
You need to install `ffmpeg` and make sure it's added in your PATH.

https://github.com/HoloArchivists/hollow_memories#installing-python-and-ffmpeg-using-chocolatey

**Comment by urdtex** [comment]
apparently i just need to restart my pc and it working now 👍 
![Capture](https://github.com/HoloArchivists/fc2-live-dl/assets/134232222/4d68ef6a-1e83-45bc-a201-6916a9275d0c)
