### ISSUE TITLE
Add arm64 docker image

### ISSUE THREAD

**Issue by aozaki-kuro** [HoloArchivists/fc2-live-dl#45]
Hello,

I am truly grateful for this tool, which has freed me from the fc2 monitoring and recording.

Currently I'm in the process of migrating my server to an arm64 version. This requires building the image from scratch. Also I am trying to deploy a backup on my Raspberry Pi, which is even more time-consuming on these relatively low-performance machines.

Below is my `Dockerfile`:

```Dockerfile

FROM python:3.11-alpine

WORKDIR /app/

RUN apk add --no-cache libffi-dev gcc musl-dev

RUN apk add py3-pip ffmpeg

RUN pip install --upgrade fc2-live-dl

RUN mkdir recordings

```

May I ask if there's any ways to save the time when building the image. I'm rather unfamiliar with the Python projects so I have totally no idea besides from using `pip`.

Also, is there any possibility that an arm64 image will be made available in the near future? Thank you 🥺

**Comment by hizkifw** [comment]
Hi, I've added an arm64 image in the CI workflow. Once it's finished building you should be able to use the same tag for both x86_64 and arm64.

**Comment by aozaki-kuro** [comment]
Tested and running perfectly on my arm64 server! Thank you 👏
