### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'autofc2.json'

### ISSUE THREAD

**Issue by Kaiay** [HoloArchivists/fc2-live-dl#49]
Hello. I am trying to move fc2-live-dl from windows to my new synology nas.
I following the [Running autofc2 with Docker](https://github.com/HoloArchivists/fc2-live-dl#running-autofc2-with-docker) part, using docker-compose.yml and try to make it but stuck at Permission Error. I tried to fix it myself by google some information e.g. create a new user group call docker and modify the owns of docker.sock file. But I'm still can't get out of this error. May I get some help here? Thank you. Logs is in the zip file.
[tools-autofc2-1.zip](https://github.com/HoloArchivists/fc2-live-dl/files/12722112/tools-autofc2-1.zip)

**Comment by hizkifw** [comment]
Can you paste here your `docker-compose.yml` file?

**Comment by Kaiay** [comment]
`# Sample docker-compose.yml file for autofc2
# Check the README for more information
version: '3'
services:
  autofc2:
    image: ghcr.io/holoarchivists/fc2-live-dl:latest
    command: autofc2
    volumes:
    - ./autofc2.json:/app/autofc2.json:ro
    - ./recordings:/recordings
    restart: unless-stopped
    environment:
    # Feel free to update this to your local timezone. This setting influences
    # the timestamps on the program's logs.
    - TZ=Asia/Hong_Kong
`

**Comment by hizkifw** [comment]
Hi, are you still facing the issue? Can you try to update the permissions for the `autofc2.json` file? e.g. `sudo chmod 777 autofc2.json`

**Comment by Kaiay** [comment]
[admiring_brown.csv](https://github.com/HoloArchivists/fc2-live-dl/files/15246355/admiring_brown.csv)
It can run now but gives tons log of error :/

**Comment by hizkifw** [comment]
Seems to be an issue with your network. I'm not familiar enough with Synology, but a quick search of the error seems to show it might have something to do with proxy setups.

Make sure you can access live.fc2.com from your NAS, maybe try running an Ubuntu docker image and seeing if you can access FC2 from there.
